"""Enumerations for the Canonical Telemetry Model.

Defines quality flags, measurement provenance classifications, and current flow states.
"""

from enum import Enum


class TelemetryQuality(str, Enum):
    """Quality and validity status of a telemetry reading or snapshot.

    Allows downstream estimators and digital twin core logic to distinguish
    between trusted, degraded, invalid, unavailable, or stale measurements.
    """

    VALID = "VALID"              # Sensor reading confirmed valid and physically plausible
    DEGRADED = "DEGRADED"        # Sensor reading available but with higher noise or jitter
    INVALID = "INVALID"          # Sensor reading corrupted, failed CRC, or unphysical
    UNAVAILABLE = "UNAVAILABLE"  # Sensor reading was not provided by hardware / offline
    STALE = "STALE"              # Measurement timestamp exceeds expected freshness window


class MeasurementProvenance(str, Enum):
    """Origin and computation method of a telemetry quantity."""

    MEASURED = "MEASURED"        # Direct physical sensor hardware measurement
    ESTIMATED = "ESTIMATED"      # State estimator / observer calculation (e.g. EKF SOC)
    SYNTHETIC = "SYNTHETIC"      # Generated by simulation engine or testbench replay
    DERIVED = "DERIVED"          # Mathematical derivation from raw measurements (e.g. P = V * I)


class CurrentFlowDirection(str, Enum):
    """Operational macro current flow state of a battery pack."""

    CHARGING = "CHARGING"        # Current flowing into the battery pack
    DISCHARGING = "DISCHARGING"  # Current flowing out of the battery pack
    IDLE = "IDLE"                # Zero or sub-threshold quiescent current
